version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - 4171:4171
  event_storage:
    image: couchbase
    ports: 
      - 8091-8094:8091-8094
      - 11210:11210
  elasticsearch:
    image: elasticsearch:6.6.1
    networks: 
      - searching
    ports:
      - 9200:9200
      - 9300:9300
    environment: 
      - discovery.type=single-node

networks: 
  searching:
